version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-flowtype
    versions:
    - 5.2.1
    - 5.2.2
    - 5.3.0
    - 5.3.1
    - 5.4.0
    - 5.6.0
    - 5.7.0
    - 5.7.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: flow-remove-types
    versions:
    - 2.144.0
    - 2.145.0
    - 2.146.0
    - 2.147.0
    - 2.148.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
